-- ============================================================
-- Seed default users into Supabase Auth + app_users
-- Run AFTER 001_initial_schema.sql
-- ============================================================
-- NOTE: Use Supabase Dashboard → Authentication → Users to create
-- these users with the given emails/passwords, OR use the
-- Admin API. The SQL below only populates app_users assuming
-- auth.users already exist.
--
-- Default credentials:
--   admin     / admin123     (role: admin)
--   mehmet    / 1234         (role: field)
--   ali       / 1234         (role: field)
--   hasan     / 1234         (role: field)
--   murat     / 1234         (role: field)
--   isri      / isri2024     (role: customer)
--
-- Email format: <username>@cam-montaj.internal
-- ============================================================

-- This is handled automatically by POST /api/users endpoint (admin only)
-- Or create manually in Supabase Dashboard
