uploads = []

[[generated]]
id = "1CBm7EBGwon4Hu2dS7cGa"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "n2QZ5AvlnfYScpCHj1DEj"
uri = "file://artifacts/cam-montaj-sunum/public/hero-install.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4uDaWfT4MfnqXKxx7QUIH"
uri = "file://artifacts/cam-montaj-sunum/public/phone-app.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "UQKQaRb0-3lwWEBbyYDuP"
uri = "file://SUNUCU-KILAVUZU.md"
type = "text"
title = "Sunucu Kılavuzu"

[[outputs]]
id = "2UZbeY4b3GQaZGvUj8_vY"
uri = "file://.local/outputs/Mobile-Developer-Assistant.pdf"
type = "pdf"
title = "Mobile Developer Assistant.pdf"

[[outputs]]
id = "H2WSHDhe4jUsNp4quyAWn"
uri = "file://.local/outputs/Mobile-Developer-Assistant.pptx"
type = "slides"
title = "Mobile Developer Assistant.pptx"
